### ISSUE TITLE
Set "open terminal" shortcut for GNOME

### ISSUE THREAD

**Issue by fwilhe** [fwilhe/system-automation#3]
I like to set <kbd>CONTROL</kbd> + <kbd>ALT</kbd> + <kbd>T</kbd> to open a new terminal (maximized). 

I did not find out yet how this can be done programmatically (`gesettings`, `dconf` or similar?).

This should be part of the `desktop.yml`  playbook.

**Comment by fwilhe** [comment]
Found out how to do it with `gsettings`: https://gist.github.com/fwilhe/2f1f1878113883535156e230cba62bed

Thanks for the pointer to the solution, @tkrille!

Will implement that in this project soon.

**Comment by fwilhe** [comment]
Idea: The creation of key bindings could be encapsulated in a separate module.

**Comment by tkrille** [comment]
Nice, thanks for the full implementation.

**Comment by fwilhe** [comment]
I'm afraid this solution does apparently not work. I don't know yet what's wrong. The keybindings is set in the gnome control center, but it does not open a terminal.

Possible alternative solutions:

* Run a shell script that runs `gsettings`
* Write a custom ansible module just for setting the keybindings
